# Generated by Django 5.2.1 on 2025-06-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='vacation',
            unique_together={('country', 'start_date', 'end_date')},
        ),
    ]
