# Generated by Django 5.2.1 on 2025-06-28 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations_app', '0002_alter_country_country_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='vacation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='vacations_app.vacation'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
