# Generated by Django 5.2.1 on 2025-07-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations_app', '0004_alter_likes_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacation',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterField(
            model_name='vacation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vacation_images/'),
        ),
    ]
