# Generated by Django 5.2.1 on 2025-07-14 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations_app', '0005_alter_vacation_options_alter_vacation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, message='Description must be at least 10 characters')]),
        ),
    ]
